[INFO] [2019-03-29 15:48:18,017] logger.py [line:132] : 测试用例已自动生成完毕, 文件: Test.py -> 具体测试用例:test_bot_create_bot
[DEBUG] [2019-03-29 15:48:18,302] logger.py [line:132] : {'relevant_parameter': ['Host'], 'description': '创建机器人', 'method': 'post', 'url': 'https://192.168.1.104:10033/api/admin/portal/botmanager/createbot', 'json': {'BotId': '7d80cb5f-82b3-4202-9d73-7fbae428b377'}, 'headers': {'Content-Type': 'application/json; charset=utf-8', 'Access-Token': '32C42E8E8CA5FA22C3A98AEB08D3D20A5E4C3969E534F0BAF6C3F458410791E9'}, 'assert': {'ErrorCodes': [{'ErrorCode': 'PE00001', 'ErrorMessage': 'Bot正在创建中'}]}, 'check_db': None}
[INFO] [2019-03-29 15:48:18,303] logger.py [line:132] : 接受POST的请求参数为{
    "url": "https://192.168.1.104:10033/api/admin/portal/botmanager/createbot",
    "headers": {
        "Content-Type": "application/json; charset=utf-8",
        "Access-Token": "32C42E8E8CA5FA22C3A98AEB08D3D20A5E4C3969E534F0BAF6C3F458410791E9"
    },
    "json": {
        "BotId": "7d80cb5f-82b3-4202-9d73-7fbae428b377"
    },
    "data": null,
    "files": null
}
